### ISSUE TITLE
로그인 및 앱 에러 해결 및 앨범 권한 설정

### ISSUE THREAD

**Issue by parkinghun** [gambler-iOS/gambler#108]
## Feature 작업 사항을 입력해주세요.
앱 시작 시 나타나는 에러 및 로그인 로직 보강, 앨범 권한 설정

## Description

설명을 작성하세요.

Todo
- [x] 앱 시작 시 Logging Error 해결 (참고- #103 )
- [x] 로그인 무한 로딩 해결 (참고 - #106)
- [x] 로그인 뷰 처리 해결 (참고 - #109 ) 
  - 그러나 HomeView에 navigationDestinaion이 선언되어 돌아가면 홈 뷰로 감
- [x] 앨범 이동 시 권한 설정 - PhotosPicker는 process 없이 돌아가므로 라이브러리 액세스를 요청할 필요가 없습니다!
- [x] 고객센터 신고 시 - 이미지가 있으면 토스트 메시지 두 번 뜨는 문제

ETC
기타사항
