### ISSUE TITLE
Map UI기능 마무리

### ISSUE THREAD

**Issue by da-hye0** [gambler-iOS/gambler#41]
## Feature 
Map 마무리 기능 추가

## Description
지도파트 뷰 마무리 단계 & 내주변 로직 최대한 구현하기

### Todo
- [x] 에셋추가 (내위치마커, 내위치버튼) 
- [x] 마커 사이즈 변경(extension 추가)
- [x] 위치승인 앱 진입할때로 변경
- [x] 맵 띄워질 때 유저 위치 마커 draw 시점 고민해보기(지도 resize될때 draw)
- [x] Camera level 사용자 조작한 level로 고정
- [x] fullSheet, 닫기버튼 추가 ->  닫혀있을때 뷰 뺐음
- [x] floatingView 추가
- [x] 내위치 마커라도 경쟁순위 젤 상위로 바꿔줌
- [x] 마커 클릭시 카메라 움직인 후에 마커 크기 변경 vs 카메라 움직일때 마커 애니메이션 주기 
       카메라, 마커 동시로 바꿈(동작이 느린 느낌이 들어서..)
- [x] 내주변 로직구현
- [x] 카카오 워터마크 offset -> 필요없어짐
- [x] 내위치 버튼 offset 
- [x] floatingView 데이터 전달
- [x]  progressView

### 추후 구현사항
- 풀스크린 커스텀시트로 만들기
- 맵 카메라 초점 3/5지점으로 변경
- #51 
- #52

**Comment by da-hye0** [comment]
Map
